Push bash sciprt polishing

diff --git a/.github/workflows/commit.yaml b/.github/workflows/commit.yaml
--- a/.github/workflows/commit.yaml
+++ b/.github/workflows/commit.yaml
@@ -53,18 +53,21 @@ jobs:
           REMOTE_REPO="https://oauth2:${{ secrets.TRIGGER_COMMIT_ON_MAIN }}@github.com/${{ github.repository }}.git"
 
           MAX_RETRIES=5
-          COUNT=0
-          while ! git push "$REMOTE_REPO" "HEAD:$TARGET_BRANCH"; do 
-            if [ $COUNT -ge $MAX_RETRIES ]; then
-              echo "Failed to push changes after $MAX_RETRIES attempts."
-              exit 1
+          for COUNT in $(seq 1 $MAX_RETRIES); do
+            if git push "$REMOTE_REPO" "HEAD:$TARGET_BRANCH"; then
+              echo "Push successful on attempt $COUNT."
+              break
             fi
-            COUNT=$((COUNT + 1))
             echo "Push failed, retrying... ($COUNT/$MAX_RETRIES)"
             git pull --rebase "$REMOTE_REPO" "$TARGET_BRANCH"
             sleep 5
           done
 
+          if [ $COUNT -eq $MAX_RETRIES ]; then
+            echo "Failed to push changes after $MAX_RETRIES attempts."
+            exit 1
+          fi
+          
       - name: Get commit hash
         run: |
           echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
