체크 python 스크립트로 변경

diff --git a/.github/workflows/commit.yaml b/.github/workflows/commit.yaml
--- a/.github/workflows/commit.yaml
+++ b/.github/workflows/commit.yaml
@@ -23,35 +23,31 @@ jobs:
         uses: actions/checkout@v4
         with:
           token: ${{ secrets.TRIGGER_COMMIT_ON_MAIN }}
-      - name: Check maps
-        if: ${{ env.CORE_VERSION_MAP && env.DATA_PACK_VERSION_MAP }}
-        id: check_maps
+      - name: Check ore version map
+        id: check-ore-version-map
+        if: ${{ env.CORE_VERSION_MAP }}
+        continue-on-error: true
         run: |
-          check_map() {
-            local name="$1"
-            local map="$2"
-
-            # 하이픈 '-' 포함 여부 확인
-            IFS=';' read -ra VALUES <<< "$map"
-            for VALUE in "${VALUES[@]}"; do
-              if [[ ! "$VALUE" =~ - ]]; then
-                echo "오류: $name에 하이픈 '-'이 포함되지 않은 값이 있습니다: $VALUE"
-                exit 1
-              fi
-            done
-
-            # 중복된 키 확인
-            keys=$(echo "$map" | tr ';' '\n' | sed 's/-.*//')
-            duplicates=$(echo "$keys" | sort | uniq -d)
-            if [[ -n "$duplicates" ]]; then
-              echo "오류: $name에 중복된 키가 있습니다: $duplicates"
-              exit 1
-            fi
-          }
-
-          [ -n "$CORE_VERSION_MAP" ] && check_map "CoreVersionMap" "$CORE_VERSION_MAP"
-          [ -n "$DATA_PACK_VERSION_MAP" ] && check_map "DataPackVersionMap" "$DATA_PACK_VERSION_MAP"
-
+          error=$(python3 check-map-data.py -name "CoreVersionMap" -data "${{ env.CORE_VERSION_MAP }}" || true)
+          if [ -n "$error" ]; then
+            echo "error=$error" >> $GITHUB_OUTPUT
+            exit 1
+          fi
+      - name: Check data pack version map
+        id: check-data-pack-version-map
+        if: ${{ env.DATA_PACK_VERSION_MAP }}
+        continue-on-error: true
+        run: |
+          error=$(python3 check-map-data.py -name "DataPackVersionMap" -data "${{ env.DATA_PACK_VERSION_MAP }}" || true)
+          if [ -n "$error" ]; then
+            echo "error=$error" >> $GITHUB_OUTPUT
+            exit 1
+          fi
+      - name: Final check
+        if: ${{ steps.check-ore-version-map.outcome == 'failure' || steps.check-data-pack-version-map.outcome == 'failure' }}
+        run: |
+          echo "One or more checks failed. Exiting workflow."
+          exit 1
       - name: Update BOT.md
         run: |
           echo "This is a test commit from the **commit workflow**." > BOT.md
