잡 간의 failure도 잡을 수 있는지 실험

diff --git a/.github/workflows/failure-test.yaml b/.github/workflows/failure-test.yaml
--- a/.github/workflows/failure-test.yaml
+++ b/.github/workflows/failure-test.yaml
@@ -9,18 +9,23 @@ on:
 
 
 jobs:
+  fail-job:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail step
+        run: exit 1
   can-failure-catch-previous-failed-ones:
     runs-on: ubuntu-latest
     steps:
-      - name: fail step1
-        id: step1
-        run: exit 1
+      # - name: fail step1
+      #   id: step1
+      #   run: exit 1
       - name: success step1
         id: step2
         run: echo "This step succeeded"
-      - name: fail step2
-        id: step3
-        run: exit 1
+      # - name: fail step2
+      #   id: step3
+      #   run: exit 1
       - name: success step2
         id: step4
         run: echo "This step succeeded"
@@ -28,7 +33,5 @@ jobs:
         if: ${{ failure() }}
         run: |
           echo "A previous step has failed"
-          echo "outcome of step1: ${{ steps.step1.outcome }}"
           echo "outcome of step2: ${{ steps.step2.outcome }}"
-          echo "outcome of step3: ${{ steps.step3.outcome }}"
           echo "outcome of step4: ${{ steps.step4.outcome }}"
